#!/usr/bin/env python3


def traversing():
    for code in range(0x10000):
        if not 0xd800 <= code <= 0xdfff:
            print("{0:04x}: [{1:s}]".format(code, chr(code)))
        else:
            print("{0:04x}: [{1:s}]".format(code, ""))
    return


def main():
    try:
        traversing()
    except Exception as _:
        pass
    return


if __name__ == '__main__':
    main()
